menu:
  #Archives: /archives
#  归档: /projects
  关于我: /aboutme
rss: /atom.xml
description: 爱好电影、音乐和书籍，尤其喜爱许巍、李健及王小波。擅长Java，JavaScript，喜欢用NodeJs编写一些有趣的应用。关注互联网、科技、敏捷开发以及JavaNIO。
social:
  weibo:
  github: https://github.com/ThinkerH
  stack_overflow: 
  facebook:
  twitter:
  google_plus:

page_comment: true
logo: /images/logo.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-blue

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: hslife

google_analytics: UA-42596364-1
favicon: /images/favicon.png
